# 03-quarkus-panach-ThomasAntensteiner

## deployment
* start database (docker)
** docker run --name postgres -p 5432:5432 -e POSTGRES_USER=app -e POSTGRES_PASSWORD=passme postgres
* start quarkus
** mvn quarkus:dev
** or in the IntelliJ

## Project Erklärung
### create Project

----
 mvn io.quarkus:quarkus-maven-plugin:0.11.0:create \
        -DprojectGroupId=at.htl \
        -DprojectArtifactId=quarkus-panache-ThomasAnt
----

### application.properties anpassen

----
quarkus.datasource.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username = app
quarkus.datasource.password = passme
----

### dependencies hinzufügen

----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm-panache</artifactId>
</dependency>
----

### PanachEntity Beispiel

----
@Entity
public class Graveyard extends PanacheEntity {
    public String name;
    public String location;
    public Long numberOfGraves;

    public Graveyard() {
    }
}
----

### Init Bean Beispiel

----
@ApplicationScoped
public class InitBean {

    @Transactional
    void init(@Observes StartupEvent ev){
        System.out.println("Init");
        Graveyard graveyard = new Graveyard();
        graveyard.location = "Linz";
        graveyard.name = "St. Barbara";
        graveyard.numberOfGraves = 20000L;

        Graveyard graveyard2 = new Graveyard();
        graveyard2.location = "Leonding";
        graveyard2.name = "hey";
        graveyard2.numberOfGraves = 10000L;

        graveyard2.persist();
        graveyard.persist();
    }
}
----
### Panache Abfragen
----
//get a list of all graveyards and print them
Graveyard.listAll().forEach(g -> System.out.println(g));
//find by Id + Ausgabe
System.out.println(Graveyard.findById(1L));
//Ausgabe der Anzahl der Einträge
System.out.println( Graveyard.count());
//Selec Satement
Graveyard.find("select g from Graveyard g");
----

#### pondo zu NamedQueries -> static methodes
----
public static List<Graveyard> findByLocation(String location){
    return list("location",location);
}
----
----
Graveyard.findByLocation("Linz").forEach(g -> System.out.println(g));
----

### Panach Datenzugriff vs Hibernate Datenzugriff

Bei Panach wird im Gegensatz zu Hibernate kein EntityManager benötigt sonder es wird einfach die persist Methode der PanachEntität aufgerufen.
Außerdem muss bei Panach die Id nicht manuell erstellt werden sonder ein surrogate key wird von der PanachEntity vererbt.
Die Static Methoden bei Panach sind meiner Meinung nach übersichtlicher als die NamedQueries von Hibernate.
Weiters sind die vorgefertigten Methoden bei Panach wie z.B. getById sehr hilfreich.
Panach besitzt aber kein merge, wodurch das updaten etwas komplizierter ist.

### Panach CRUD (Beispiel Graveyard)
g ist im Beispiel der Input Graveyard und id die Input Id

#### POST (CREATE)
----
Graveyard.persist(g);
----
#### GET ALL (READ)
----
Graveyard.listAll()
----
#### GET By ID (READ)
----
Graveyard.findById(id)
----
#### PUT (UPDATE)
die persistierte Entität muss gelesen werden um die Properties ändern zu können.
----
Graveyard graveyard = Graveyard.findById(g.id);
graveyard.location = g.location;
graveyard.name = g.name;
graveyard.numberOfGraves = g.numberOfGraves;
----
#### DELETE
----
Graveyard.delete("id",id);
----

### Add Swagger UI
add maven dependency
----
mvnw quarkus:add-extension -Dextensions="openapi"
----
chanche Swagger path (into application.json): default("swagger-ui") +
----
quarkus.smallrye-openapi.path=/swagger
----

